# Generated by Django 4.1 on 2023-07-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='date and time the task was created')),
                ('title', models.CharField(max_length=250, verbose_name='title of task')),
                ('description', models.TextField(verbose_name='description of task')),
                ('completed', models.BooleanField(default=False, verbose_name='flag indicating whether the task is running')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
